import type { LucideProps, LucideIcon } from "lucide-react";
import {
  AlarmClock,
  BadgeDollarSign,
  Binary,
  Barcode,
  Braces,
  CalendarCheck,
  CalendarClock,
  CalendarRange,
  CaseSensitive,
  CaseUpper,
  Calculator,
  CircleDollarSign,
  Clock3,
  CodeXml,
  Database,
  Dices,
  FileCog,
  FileCode2,
  FileDigit,
  FileJson2,
  Fingerprint,
  Globe2,
  Hash,
  ImageDown,
  ImageUp,
  KeyRound,
  KeySquare,
  Languages,
  Link2,
  ListFilter,
  LockKeyhole,
  NotebookText,
  Palette,
  QrCode,
  Rabbit,
  Regex,
  ScanLine,
  ScanText,
  Scale,
  ScreenShare,
  ShieldEllipsis,
  Shuffle,
  Sparkles,
  SpellCheck,
  SquareCode,
  Stamp,
  SwatchBook,
  Eraser,
  IdCard,
  WandSparkles,
  WalletCards,
  Webhook,
} from "lucide-react";

import type { CategorySlug, ToolSlug } from "@/lib/tools";
import { cn } from "@/lib/utils";

const categoryIcons: Record<CategorySlug, LucideIcon> = {
  generate: WandSparkles,
  image: ImageUp,
  encrypt: LockKeyhole,
  time: Clock3,
  convert: Scale,
  finance: WalletCards,
  text: ScanText,
  dev: SquareCode,
};

const toolIcons: Record<ToolSlug, LucideIcon> = {
  "rand-password": KeyRound,
  qrcode: QrCode,
  "screen-record": ScreenShare,
  "random-number": Dices,
  guid: Fingerprint,
  "random-group": Shuffle,
  watermark: Stamp,
  "image-compress": ImageDown,
  "qrcode-decode": ScanLine,
  barcode: Barcode,
  md5: Fingerprint,
  "file-md5": FileDigit,
  hmac: ShieldEllipsis,
  sha: Hash,
  aes: LockKeyhole,
  rabbit: Rabbit,
  des: KeySquare,
  rc4: KeyRound,
  base64: Binary,
  unicode: Languages,
  url: Link2,
  timestamp: Clock3,
  calculation: CalendarRange,
  world: Globe2,
  "working-day": CalendarCheck,
  "batch-timestamp": CalendarClock,
  "unit-converter": Scale,
  "english-amount": BadgeDollarSign,
  "sum-list": Calculator,
  loan: WalletCards,
  rmb: CircleDollarSign,
  "text-dedupe": ListFilter,
  "emoji-clean": Eraser,
  "id-card-cn": IdCard,
  "simplified-traditional": Languages,
  pinyin: SpellCheck,
  pluralize: CaseSensitive,
  "english-case": CaseUpper,
  "cn-en": Languages,
  trim: ScanText,
  regex: Regex,
  "md-html": FileCode2,
  json: FileJson2,
  "json-to-types": Braces,
  css: Palette,
  js: SquareCode,
  html: CodeXml,
  sql: Database,
  crontab: AlarmClock,
  "naming-converter": NotebookText,
  "color-converter": SwatchBook,
  websocket: Webhook,
  "go-struct-json": Braces,
  less2css: FileCog,
  binary: Binary,
};

export function CategoryIcon({
  slug,
  className,
  ...props
}: LucideProps & { slug: CategorySlug }) {
  const Icon = categoryIcons[slug] ?? Sparkles;
  return <Icon className={cn("size-4", className)} {...props} />;
}

export function ToolIcon({
  slug,
  className,
  ...props
}: LucideProps & { slug: ToolSlug }) {
  const Icon = toolIcons[slug] ?? Sparkles;
  return <Icon className={cn("size-4", className)} {...props} />;
}
